window.presentationScroll=window.ScrollCraft?.mount(document);
const chapters=[...document.querySelectorAll('.chapter')];
const dialog=document.querySelector('#index-dialog');
const indexButton=document.querySelector('#contents');
const motionButton=document.querySelector('#motion');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let motionOff=reduced.matches;
let current=0;
let presenting=false;
let timerStarted=0,timerElapsed=0;
const headings=chapters.map(s=>s.querySelector('h1,h2').innerText.replace(/\n/g,' '));
const indexLinks=document.querySelector('.index-links');
chapters.forEach((section,i)=>{const link=document.createElement('a');link.href='#'+section.id;const time=document.createElement('time');time.textContent=section.dataset.time;const label=document.createElement('span');label.textContent=headings[i];link.append(time,label);indexLinks.append(link);link.addEventListener('click',()=>{dialog.close();go(i)});});
function go(i){i=Math.max(0,Math.min(chapters.length-1,i));chapters[i].scrollIntoView({behavior:motionOff?'instant':'smooth',block:'start'});history.replaceState(null,'','#'+chapters[i].id);}
function updateCurrent(){let best=0;chapters.forEach((s,i)=>{if(s.getBoundingClientRect().top<=innerHeight*.4)best=i});current=best;const group=chapters[current].dataset.topic;document.querySelectorAll('.chapter-nav a').forEach(a=>{const active=a.dataset.group===group||(group==='Perspective'&&a.dataset.group==='Opening');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')});document.querySelector('#current-title').textContent=group;document.querySelector('#previous').disabled=current===0;document.querySelector('#next').disabled=current===chapters.length-1;}
let queued=false;addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(()=>{updateCurrent();queued=false})}},{passive:true});updateCurrent();
indexButton.addEventListener('click',()=>{dialog.showModal();indexButton.setAttribute('aria-expanded','true')});document.querySelector('#close-index').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{indexButton.setAttribute('aria-expanded','false');indexButton.focus()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
function setMotion(off){motionOff=off;document.body.classList.toggle('motion-off',off);motionButton.setAttribute('aria-pressed',String(off));motionButton.querySelector('span').textContent=off?'off':'on';document.dispatchEvent(new CustomEvent('motionchange',{detail:{off}}));}setMotion(motionOff);motionButton.addEventListener('click',()=>setMotion(!motionOff));reduced.addEventListener('change',e=>setMotion(e.matches));
document.querySelector('#present').addEventListener('click',()=>{presenting=!presenting;document.body.classList.toggle('presenting',presenting);document.querySelector('.presenter-controls').hidden=!presenting;document.querySelector('#present').setAttribute('aria-pressed',String(presenting));go(current)});
function advanceSystem(direction){const next=phase+direction;if(next<0||next>2)return false;setPhase(next,true);if(!motionOff&&innerWidth>600){const top=system.getBoundingClientRect().top+scrollY;const travel=Math.max(1,system.offsetHeight-innerHeight);scrollTo({top:top+[0.05,0.45,0.85][next]*travel,behavior:'instant'})}return true}
function advance(direction){updateCurrent();if(chapters[current].id==='q11'&&window.advanceAudit?.(direction))return;if(direction<0&&chapters[current-1]?.id==='system'){current-=1;phase=3;advanceSystem(-1);history.replaceState(null,'','#system');return}if(chapters[current].id==='system'&&advanceSystem(direction))return;if(window.advanceNarrative?.(chapters[current],direction))return;go(current+direction)}
document.querySelector('#previous').addEventListener('click',()=>advance(-1));document.querySelector('#next').addEventListener('click',()=>advance(1));
addEventListener('keydown',e=>{if(dialog.open||e.altKey||e.ctrlKey||e.metaKey||e.target.closest('input,textarea,select,[contenteditable]'))return;if(e.target.closest('button,a')&&[' ','Enter'].includes(e.key))return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();advance(1)}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();advance(-1)}if(e.key==='Home'){e.preventDefault();go(0)}if(e.key==='End'){e.preventDefault();go(chapters.length-1)}if(e.key==='Escape'&&presenting)document.querySelector('#present').click();});
const timer=document.querySelector('#timer');timer.addEventListener('click',()=>{if(timerStarted){timerElapsed+=Date.now()-timerStarted;timerStarted=0}else timerStarted=Date.now();renderTimer()});document.querySelector('#reset-timer').addEventListener('click',()=>{timerStarted=0;timerElapsed=0;renderTimer()});function renderTimer(){const sec=Math.floor((timerElapsed+(timerStarted?Date.now()-timerStarted:0))/1000);timer.textContent=(timerStarted?'Pause ':'Start ')+String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');timer.style.color=sec>=1500?'#ffd6a2':'';}setInterval(renderTimer,1000);
const descriptions=['Start with shared foundations, agreed with engineering.','Primitive values define the foundations. Semantic names explain their purpose.','Adapt brand, product, and locale through context-specific tokens, while keeping the shared foundation.'];
let phaseOverride=null;let phase=0;const system=document.querySelector('#system');
function setPhase(p,user=false){phase=p;if(user)phaseOverride=p;document.querySelectorAll('[data-phase]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.phase)===p)));document.querySelector('#system-description').textContent=descriptions[p];document.querySelector('.architecture').dataset.systemPhase=p;document.dispatchEvent(new CustomEvent('systemphase',{detail:{phase:p}}));}
document.querySelectorAll('[data-phase]').forEach(b=>b.addEventListener('click',()=>setPhase(+b.dataset.phase,true)));
let systemQueued=false;addEventListener('scroll',()=>{if(systemQueued)return;systemQueued=true;requestAnimationFrame(()=>{systemQueued=false;const r=system.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight){phaseOverride=null;return}if(phaseOverride!==null||motionOff||innerWidth<=600)return;const travel=Math.max(1,system.offsetHeight-innerHeight);const p=Math.max(0,Math.min(1,-r.top/travel));const next=p<.2?0:p<.72?1:2;if(next!==phase)setPhase(next);document.dispatchEvent(new CustomEvent('systemscroll',{detail:{progress:p}}))})},{passive:true});
// Bespoke restrained depth. Text is deliberately outside the moving planes.
let frameQueued=false;function parallax(){frameQueued=false;if(motionOff)return;const y=scrollY;document.querySelector('.orbit-back').style.transform=`translateY(${Math.min(y*.12,110)}px) rotateX(50deg) rotateZ(-25deg)`;document.querySelector('.orbit-front').style.transform=`translateY(${Math.min(y*.24,180)}px) rotateX(50deg) rotateZ(-25deg)`;const hr=document.querySelector('.hero-render');if(hr)hr.style.transform=`translateY(${Math.min(y*.08,70)}px)`;}
addEventListener('scroll',()=>{if(!frameQueued){frameQueued=true;requestAnimationFrame(parallax)}},{passive:true});
